version: '3.8'

services:
  codenames:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APPWRITE_ENDPOINT=${NEXT_PUBLIC_APPWRITE_ENDPOINT}
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
      - NEXT_PUBLIC_APPWRITE_DATABASE_ID=${NEXT_PUBLIC_APPWRITE_DATABASE_ID}
      - NEXT_PUBLIC_APPWRITE_GAMES_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_GAMES_COLLECTION_ID}
      - NEXT_PUBLIC_APPWRITE_PLAYERS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_PLAYERS_COLLECTION_ID}
    restart: unless-stopped
